In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

os.makedirs("/content/drive/MyDrive/cryptguard", exist_ok=True)
os.chdir("/content/drive/MyDrive/cryptguard")

print("Working directory:", os.getcwd())

Working directory: /content/drive/MyDrive/cryptguard

In [ ]:
!cp /content/drive/MyDrive/cicids.zip /content/drive/MyDrive/cryptguard/

In [ ]:
!unzip /content/drive/MyDrive/cryptguard/cicids.zip -d /content/drive/MyDrive/cryptguard/

Archive:  /content/drive/MyDrive/cryptguard/cicids.zip
  inflating: /content/drive/MyDrive/cryptguard/cic-collection.parquet

In [ ]:
!pip install pyarrow fastparquet scikit-learn pandas

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: fastparquet in /usr/local/lib/python3.12/dist-packages (2025.12.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.0.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet) (26.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

import joblib

In [ ]:
df = pd.read_parquet("/content/drive/MyDrive/cryptguard/cic-collection.parquet")

print("Dataset loaded successfully")

Dataset loaded successfully

In [ ]:
print("Dataset shape:")
print(df.shape)

Dataset shape:
(9167581, 59)

In [ ]:
print("Columns in dataset:\n")
print(df.columns.tolist())

Columns in dataset:

['Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Fwd Packets Length Total', 'Bwd Packets Length Total', 'Fwd Packet Length Max', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Packet Length Max', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'SYN Flag Count', 'URG Flag Count', 'Avg Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init Fwd Win Bytes', 'Init Bwd Win Bytes', 'Fwd Act Data Packets', 'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label', 'ClassLabel']

In [ ]:
df.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Fwd Packets Length Total,Bwd Packets Length Total,Fwd Packet Length Max,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Mean,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,ClassLabel
0,4,2,0,12.0,0.0,6.0,6.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,Benign
1,1,2,0,12.0,0.0,6.0,6.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,Benign
2,3,2,0,12.0,0.0,6.0,6.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,Benign
3,1,2,0,12.0,0.0,6.0,6.00000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,Benign
4,609,7,4,484.0,414.0,233.0,69.14286,111.967896,207.0,103.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign,Benign

In [ ]:
df_sample = df.sample(200000, random_state=42)

print("Sampled dataset shape:")
print(df_sample.shape)

Sampled dataset shape:
(200000, 59)

In [ ]:
df_sample['Label'].value_counts()

Label
Benign                  157280
DDoS-LOIC-HTTP           12362
DoS-Hulk                  6834
DDoS-HOIC                 4274
Botnet                    3228
DDoS                      2805
DDoS-NTP                  2617
DDoS-TFTP                 2102
Bruteforce-SSH            2082
Infiltration              2058
DoS-Goldeneye             1124
DDoS-Syn                  1015
DDoS-UDP                   611
DoS-Slowloris              307
DDoS-MSSQL                 258
DDoS-UDPLag                164
Bruteforce-FTP             144
DDoS-Ddossim               136
DoS-Slowhttptest           131
DDoS-DNS                    82
DoS-Slowread                66
Portscan                    52
DDoS-SNMP                   44
DDoS-LDAP                   42
DoS-Slowheaders             41
DDoS-Slowloris              38
Webattack-bruteforce        34
Webattack-XSS               27
DDoS-NetBIOS                19
DoS-Rudy                    11
DoS-Slowbody                 8
Webattack-SQLi               4
Name: count, dtype: int64

In [ ]:
df_sample['Label'] = df_sample['Label'].apply(lambda x: 0 if x == 'Benign' else 1)

df_sample['Label'].value_counts()

Label
0    157280
1     42720
Name: count, dtype: int64

In [ ]:
X = df_sample.drop(columns=['Label', 'ClassLabel'])
y = df_sample['Label']

print("Feature shape:", X.shape)
print("Label shape:", y.shape)

Feature shape: (200000, 57)
Label shape: (200000,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (160000, 57)
Test size: (40000, 57)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (160000, 57)
Test size: (40000, 57)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

Train size: (160000, 57)
Test size: (40000, 57)

In [ ]:
rf_model = RandomForestClassifier(
    n_estimators=30,
    max_depth=None,
    n_jobs=-1,
    random_state=42
)

print("Random Forest initialized")

Random Forest initialized

In [ ]:
rf_model.fit(X_train, y_train)

print("Training complete")

Training complete

In [ ]:
model_path = "/content/drive/MyDrive/cryptguard/rf_model_v1.pkl"

joblib.dump(rf_model, model_path)

print("Model saved to Drive:", model_path)

Model saved to Drive: /content/drive/MyDrive/cryptguard/rf_model_v1.pkl

In [ ]:
y_pred = rf_model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[31526   100]
 [  461  7913]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     31626
           1       0.99      0.94      0.97      8374

    accuracy                           0.99     40000
   macro avg       0.99      0.97      0.98     40000
weighted avg       0.99      0.99      0.99     40000

In [ ]:
sample_20 = X_test.iloc[:20]

predictions = rf_model.predict(sample_20)

print(predictions)

[0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0]

In [ ]:
import time

# take 1000 random flows from test set
sample_flows = X_test.sample(1000)

start = time.time()

rf_model.predict(sample_flows)

end = time.time()

total_time = end - start

latency_per_flow = (total_time / 1000) * 1000  # milliseconds

print("Total time:", total_time, "seconds")
print("Average latency per flow:", latency_per_flow, "ms")

Total time: 0.04408717155456543 seconds
Average latency per flow: 0.04408717155456543 ms

In [ ]:
flows_per_second = 1000 / total_time

print("Throughput:", int(flows_per_second), "flows/sec")

Throughput: 22682 flows/sec

In [ ]:
flows_per_second = 1000 / total_time

print("Throughput:", int(flows_per_second), "flows/sec")

Throughput: 22682 flows/sec

In [ ]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=-1, num_parallel_tree=None, ...)

In [ ]:
y_pred_xgb = xgb_model.predict(X_test)

print(confusion_matrix(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb))

[[31602    24]
 [  442  7932]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     31626
           1       1.00      0.95      0.97      8374

    accuracy                           0.99     40000
   macro avg       0.99      0.97      0.98     40000
weighted avg       0.99      0.99      0.99     40000

In [ ]:
joblib.dump(xgb_model, "/content/drive/MyDrive/cryptguard/xgb_model.pkl")

['/content/drive/MyDrive/cryptguard/xgb_model.pkl']